CREATE TABLE IF NOT EXISTS cidades (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    area DECIMAL(10, 2) NOT NULL,
    estado_id INT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(estado_id) REFERENCES estados(id)
);

CREATE TABLE IF NOT EXISTS teste (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DROP TABLE IF EXISTS teste;

ALTER TABLE
    cidades
ADD
    FOREIGN KEY (estado_id) REFERENCES estados(id);

ALTER TABLE
    cidades CHANGE COLUMN area area DECIMAL(10, 2) NOT NULL;